# Site Information
site_name: Utilities Documents
site_url: https://utility-rblx.github.io/utility-documentation/
site_author: metamethods#0774 | InvalidData#0001
site_description: Make your life much easier with this roblox module.

# Repo Information
repo_name: utility-rblx
repo_url: https://github.com/utility-rblx/utility-documentation

# Themes
theme:
  name: material

  features:
    - content.code.annotate 

    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand

    - toc.follow
  
  palette:
    scheme: slate

  font:
    code: Consolas

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

  - def_list

  - md_in_html

  - attr_list

  - admonition

  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details

# Extra
extra:
  generator: false

extra_css:
  - stylesheets/extra.css

# Documentation Layout
nav:
    - Introduction: index.md
    - Licence: licence.md
    - Credits: credits.md
    - TODO: todo.md

    - Services:
        - services/introduction.md
        - services/http-service.md
        - services/debounce-service.md
    
    - Sub Services:
        - sub-services/introduction.md
        - Http Module:
          - sub-services/http-module/discord-webhook.md
        